# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# We don't want the docs to be published if there are any warnings,
# as they might be relevant
# https://github.com/readthedocs/readthedocs.org/issues/6837#issuecomment-607229633
sphinx:
  fail_on_warning: true

# Formats of the documentation to be built
formats:
  - htmlzip
  - pdf
  - epub

python:
   version: 3.7
   install:
   - requirements: docs/requirements.txt
